.\" Manpage for opendlv-proxy-miniature-Ping
.\" Author: Ola Benderius <ola.benderius@chalmers.se>.

.TH opendlv-proxy-miniature-Ping 1 "15 April 2017" "0.1.5" "opendlv-proxy-miniature-Ping man page"

.SH NAME
opendlv-proxy-miniature-Ping \- This module interfaces with an Ping pin at the BeagleBone Black.


.SH SYNOPSIS
.B opendlv-proxy-miniature-Ping --cid=<CID>


.SH EXAMPLES
The following command joins the container conference 111:

.B opendlv-proxy-miniature-Ping --cid=111



.SH SEE ALSO



.SH BUGS
No known bugs.



.SH AUTHOR
Ola Benderius (ola.benderius@chalmers.se)

